backend:
  name: git-gateway
  branch: main

media_folder: public/images/uploads
public_folder: /images/uploads

display_url: https://yesnoklub.net
logo_url: /images/assets/YNK_Logo.png

collections:
  - name: "events"
    label: "Events"
    folder: "content/events"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date/Time",
          name: "date",
          widget: "datetime",
          default: "",
          date_format: "D.M.YYYY",
          time_format: "hh:mm",
          format: "LLL",
          picker_utc: false,
        }
      - { label: "Venue", name: "venue", widget: "string" }
      - {
          label: "Venue URL",
          name: "venueURL",
          widget: "string",
          required: false,
        }
      - {
          label: "With (Performers/Presenters)",
          name: "with",
          widget: "string",
        }
      - {
          label: "Additional Info",
          name: "info",
          widget: "string",
          required: false,
        }
      - { label: "Flyer", name: "flyer", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - {
          label: "Documentation",
          name: "documentation",
          widget: "list",
          summary: "{{fields.image}}",
          field: { label: Image, name: image, widget: image },
          required: false,
        }
